version: '3.8'
services:
  blog:
    build: .
    image: blog:latest
    container_name: blog
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-container:3306/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - TZ=Asia/Seoul  # 시스템 타임존
      - JAVA_TOOL_OPTIONS=-Duser.timezone=Asia/Seoul
      - SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_TIME_ZONE=Asia/Seoul
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - blog-network
      - my-network
    restart: unless-stopped

# 기존 mysql container 사용
networks:
  blog-network:
    external: true  # 기존 네트워크 사용
  my-network:
    external: true