spring:
  profiles:
    active: local
---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

# 공통 설정
server:
  port: 8080

