#spring:
#  profiles:
#    active: image, local
##
#spring:
#  profiles:
#    active: jwt, image, local
#---
spring:

# aop 관련 설정
  aop:
    auto: true
    proxy-target-class: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

#decorator:
#  datasource:
#    p6spy:
#      enable-logging: true
#      multiline: true
#      logging: slf4j

## AOP 관련 설정
logging:
  level:
    HeoJin.demoBlog: DEBUG
    root: INFO


server:
  servlet:
    session:
      cookie:
        path: /
        # 로컬 테스트 중에는 주석 처리 또는 변경

        http-only: true
#        secure: false
        secure: true
        same-site: lax
        max-age: 1800

  port: 8080


## git hub Secrets 활용
cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:default-cloud-name}
  api-key: ${CLOUDINARY_API_KEY:default-api-key}
  api-secret: ${CLOUDINARY_API_SECRET:default-api-secret}



jwt:
  secret: ${JWT_SECRET}
  accesstoken:
    expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
  refreshtoken:
    expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}
