spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false  # 중복 방지를 위해 false로 변경
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true

# 로깅 설정
logging:
  level:
    org.hibernate.SQL: DEBUG  # 이것만으로 SQL 로깅
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # 파라미터 값 로그
    org.springframework.web: DEBUG  # 웹 요청/응답 로그
    HeoJin.demoBlog: DEBUG  # 본인 패키지 로그
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# P6Spy 설정 (필요시 주석 해제)
#decorator:
#  datasource:
#    p6spy:
#      enable-logging: true
#      multiline: true
#      logging: slf4j

server:
  servlet:
    session:
      cookie:
        path: /
        http-only: true
        same-site: none
        # 프로덕션용 설정 (로컬에서는 주석)
        # secure: true

  port: 8080