#spring:
#  profiles:
#    active: mysql
#---
#spring:
#  config:
#    activate:
#      on-profile: mysql

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

# 공통 설정
server:
  port: 8080

