spring:
  profiles:
    active: local
---
spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

#decorator:
#  datasource:
#    p6spy:
#      enable-logging: true
#      multiline: true
#      logging: slf4j

server:
  servlet:
    session:
      cookie:
        path: /
        same-site: none
        secure: true
  port: 8080
