#spring:
#  profiles:
#    active: mysql
#---
#spring:
#  config:
#    activate:
#      on-profile: mysql

# DockerFile, 커맨드보다 우선순위 낮음
# 혹시 모르니 주석처리

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

# 공통 설정
server:
  port: 8080

