#spring:
#  profiles:
#    active: local
---
spring:
#  config:
#    activate:
#      on-profile: local

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

#decorator:
#  datasource:
#    p6spy:
#      enable-logging: true
#      multiline: true
#      logging: slf4j

server:
  servlet:
    session:
      cookie:
        path: /
        # 로컬 테스트 중에는 주석 처리 또는 변경
        # same-site: none  # 프로덕션에서만 활성화 예정
        # secure: true     # 프로덕션에서만 활성화 예정
        http-only: false
        same-site: none # 추가로 정리하기, 생각보다 재밌음
        max-age: 1800

  port: 8080
