name: CI with on press server
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - uses: actions/checkout@v3

      - name: Build and Deploy
        run: |
          docker build -t blog:latest .
          docker stop blog || true
          docker rm blog || true
          docker run -d -p 8080:8080 \
            -e SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/test?useSSL=false&allowPublicKeyRetrieval=true \
            -e SPRING_DATASOURCE_USERNAME=Heojin \
            -e SPRING_DATASOURCE_PASSWORD=1234 \
            --name blog blog:latest